name: CI/CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  FUNCTIONS_NAME: Sugatan_Klaviyo
  TOPIC_ID: klaviyo
  REGION: us-central1

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ env.FUNCTIONS_NAME }}
          --entry-point=main
          --timeout=530
          --memory=1024MB
          --project=${{ secrets.PROJECT_ID }}
          --trigger-http
          --runtime=python38
          --service-account=${{ secrets.GCP_SA }}
          --set-env-vars=PROJECT_ID=${{ secrets.PROJECT_ID }},TOPIC_ID=${{ env.TOPIC_ID }},SBLA_PRIVATE_KEY=${{ secrets.SBLA_PRIVATE_KEY }}
