name: CI/CD
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  FUNCTION_NAME: sugatan_klaviyo
  REGION: us-central1
  QUEUE_ID: klaviyo

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ env.FUNCTION_NAME }}
          --entry-point=main
          --timeout=530
          --memory=1024MB
          --project=${{ secrets.PROJECT_ID }}
          --trigger-http
          --runtime=python39
          --service-account=${{ secrets.GCP_SA }}
          --set-env-vars=PROJECT_ID=${{ secrets.PROJECT_ID }},REGION=${{ env.REGION }},FUNCTION_NAME=${{ env.FUNCTION_NAME }},QUEUE_ID=${{ env.QUEUE_ID }},GCP_SA=${{ secrets.GCP_SA }}
